import Foundation

// Codable models for the seed JSON in Resources/Data, generated by scripts/extract_data.mjs.

// MARK: - foods.json

struct FoodsFile: Codable, Sendable {
    let nutrientKeys: [Nutrient]
    let categories: [String]
    let foods: [Food]
}

struct Food: Codable, Hashable, Sendable, Identifiable {
    let name: String
    let category: String
    let per100g: Nutrients

    var id: String { name }
    var kcal: Double { per100g.kcal }
}

// MARK: - plans.json

/// The five moments of a plan day. Raw values match the prototype and plans.json.
enum MealSlot: String, CaseIterable, Codable, Sendable {
    case breakfast = "ontbijt"
    case lunch
    case snack = "tussendoor"
    case dinner = "avond"
    case eveningSnack = "avondsnack"

    var displayName: String {
        switch self {
        case .breakfast: "Ontbijt"
        case .lunch: "Lunch"
        case .snack: "Tussendoor"
        case .dinner: "Avondeten"
        case .eveningSnack: "Avondsnack"
        }
    }
}

/// The two plan menus. Choices are stored per menu.
enum PlanMenu: String, CaseIterable, Codable, Sendable {
    /// "Gangbaar & goedkoop", the default.
    case budget
    /// "Gevarieerd".
    case varied = "variatie"

    static let `default`: PlanMenu = .budget
}

struct PlansFile: Codable, Sendable {
    struct SlotInfo: Codable, Sendable {
        let id: MealSlot
        let name: String
    }

    struct MenuInfo: Codable, Sendable {
        let name: String
        let meals: [MealSlot: [Meal]]

        private enum CodingKeys: String, CodingKey { case name, meals }

        init(name: String, meals: [MealSlot: [Meal]]) {
            self.name = name
            self.meals = meals
        }

        init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            name = try container.decode(String.self, forKey: .name)
            let raw = try container.decode([String: [Meal]].self, forKey: .meals)
            var meals: [MealSlot: [Meal]] = [:]
            for (key, value) in raw {
                guard let slot = MealSlot(rawValue: key) else {
                    throw DecodingError.dataCorruptedError(
                        forKey: .meals, in: container, debugDescription: "Unknown slot \(key)")
                }
                meals[slot] = value
            }
            self.meals = meals
        }

        func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(name, forKey: .name)
            try container.encode(
                Dictionary(uniqueKeysWithValues: meals.map { ($0.key.rawValue, $0.value) }), forKey: .meals)
        }
    }

    let slots: [SlotInfo]
    let days: [String]
    let menus: [String: MenuInfo]

    func menu(_ menu: PlanMenu) -> MenuInfo? { menus[menu.rawValue] }
}

struct Meal: Codable, Hashable, Sendable {
    let name: String
    let items: [MealIngredient]
}

struct MealIngredient: Codable, Hashable, Sendable {
    /// Name of a food in foods.json.
    let food: String
    /// Unscaled amount in grams.
    let grams: Double
}

// MARK: - supplements.json

struct SupplementsFile: Codable, Sendable {
    let supplements: [Supplement]
}

struct Supplement: Codable, Hashable, Sendable, Identifiable {
    let id: String
    let name: String
    let dose: Double
    let unit: String
    let defaultOn: Bool
    /// The nutrient this supplement adds `dose` of, e.g. vitamin D3 → vitamin D.
    let nutrient: Nutrient?
    /// Amounts per unit for combination products (multivitamin), multiplied by `dose`.
    let perUnit: Nutrients?
}

// MARK: - prices.json

struct PricesFile: Codable, Sendable {
    /// € per kg as weighed in the plan.
    let perKg: [String: Double]
    /// € per kg for foods without their own price.
    let categoryPerKg: [String: Double]
    let fallbackPerKg: Double
}

// MARK: - packs.json

struct PacksFile: Codable, Sendable {
    let aisles: [String]
    let packs: [String: Pack]
    /// Aisle for foods without their own pack, by food category.
    let categoryAisles: [String: String]
    let fallback: Pack
}

struct Pack: Codable, Hashable, Sendable {
    let aisle: String
    let singular: String
    let plural: String
    /// Grams per pack as bought.
    let grams: Double
    /// Conversion from bought weight to plan weight (e.g. dry rice → cooked rice 2.8).
    let conversion: Double
}

// MARK: - stores.json

struct StoresFile: Codable, Sendable {
    let source: String
    let stores: [Store]
    let defaultStores: [String]
}

struct Store: Codable, Hashable, Sendable {
    let name: String
    /// Price index in percent relative to the average (Consumentenbond).
    let index: Double
}
